application: linear-enigma-442
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: htdocs/static

- url: .*
  script: htdocs/index.php

skip_files:
- ^build/.*$
- ^coverage/.*$
- ^htdocs/tests/.*$
- ^vendor/phpunit/.*$
